# goreleaser.yml
project_name: arlo-dl
build:
  binary: arlo-dl
  goos:
    - linux
    - windows
    - freebsd
  goarch:
    - amd64
  ldflags: -s -w -X main.version=v{{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
nfpms:
  - homepage: https://github.com/lrstanley/arlo-dl
    maintainer: Liam Stanley <me@liamstanley.io>
    description: arlo-dl -- cli tool for downloading arlo recordings and saving them to a file
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
archives:
  - id: tgz
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
release:
  draft: true
snapshot:
  name_template: snapshot-{{.Commit}}
