# goreleaser.yml
project_name: arlo-dl
build:
  binary: arlo-dl
  goos:
    - linux
    - windows
  goarch:
    - amd64
  ldflags: -s -w -X main.version=v{{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
nfpm:
  homepage: https://github.com/lrstanley/arlo-dl
  maintainer: Liam Stanley <me@liamstanley.io>
  description: arlo-dl -- cli tool for downloading arlo recordings and saving them to a file
  license: MIT
  formats:
    - rpm
    - deb
  bindir: /usr/bin
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
snapshot:
  name_template: snapshot-{{.Commit}}
